//import { ErrlyInitializer } from '@/components/errly-initializer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/*<ErrlyInitializer />*/}
        {children}
      </body>
    </html>
  )
}
